apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 3
  template:
    metadata:
      name: httpd
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:2.4-alpine